version: '3.7'
services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --port=3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gams
      USER: 1000

  api:
    image: node:10.15
    hostname: api
    ports:
      - '3001:3001'
    volumes:
      - ../:/usr/src/service
    working_dir: /usr/src/service/packages/api
    command: ['./wait-for-it.sh', 'mysql:3306', '--', 'yarn', 'start']

  website:
    image: node:10.15
    hostname: website
    links:
      - mysql
    ports:
      - '3000:3000'
      - '1235:1235'
    volumes:
      - ../:/usr/src/service
    working_dir: /usr/src/service/packages/website
    command: yarn start:dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx
    hostname: nginx
    links:
      - api
      - website
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'

